### ISSUE TITLE
Gatsby build issue

### ISSUE THREAD

**Issue by jamesadarich** [jamesadarich/static-site-seed#25]
Looks like we're affected by gatsbyjs/gatsby#1846 in the docker build

Should be fixed by gatsby 2

Until then added an npm script patch to handle the workaround

Remove when gatsby 2 has been released

**Comment by ntnbst** [comment]
Any fix till now??

**Comment by jamesrichford** [comment]
Hi @ntnbst this is awaiting a fix from gatsby directly - I've just added a workaround - running `npm run patch:extract-text-plugin` should resolve this if you run before building for now. Hopefully we'll get a full fix soon though :)

**Comment by jamesadarich** [comment]
closed in #33
